package com.guoyuhang.wx_cms.dao.model;

import java.io.Serializable;

public class ActivitySpu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_spu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_spu.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_spu.spu_id
     *
     * @mbg.generated
     */
    private Integer spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_spu.participation
     *
     * @mbg.generated
     */
    private Byte participation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_spu.id
     *
     * @return the value of activity_spu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_spu.id
     *
     * @param id the value for activity_spu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_spu.activity_id
     *
     * @return the value of activity_spu.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_spu.activity_id
     *
     * @param activityId the value for activity_spu.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_spu.spu_id
     *
     * @return the value of activity_spu.spu_id
     *
     * @mbg.generated
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_spu.spu_id
     *
     * @param spuId the value for activity_spu.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_spu.participation
     *
     * @return the value of activity_spu.participation
     *
     * @mbg.generated
     */
    public Byte getParticipation() {
        return participation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_spu.participation
     *
     * @param participation the value for activity_spu.participation
     *
     * @mbg.generated
     */
    public void setParticipation(Byte participation) {
        this.participation = participation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityId=").append(activityId);
        sb.append(", spuId=").append(spuId);
        sb.append(", participation=").append(participation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}