package com.guoyuhang.wx_cms.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_count
     *
     * @mbg.generated
     */
    private Integer totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.expired_time
     *
     * @mbg.generated
     */
    private Date expiredTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.placed_time
     *
     * @mbg.generated
     */
    private Date placedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_img
     *
     * @mbg.generated
     */
    private String snapImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_title
     *
     * @mbg.generated
     */
    private String snapTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_items
     *
     * @mbg.generated
     */
    private Object snapItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_address
     *
     * @mbg.generated
     */
    private Object snapAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.prepay_id
     *
     * @mbg.generated
     */
    private String prepayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.final_total_price
     *
     * @mbg.generated
     */
    private BigDecimal finalTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_count
     *
     * @return the value of order.total_count
     *
     * @mbg.generated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_count
     *
     * @param totalCount the value for order.total_count
     *
     * @mbg.generated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.delete_time
     *
     * @return the value of order.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.delete_time
     *
     * @param deleteTime the value for order.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.expired_time
     *
     * @return the value of order.expired_time
     *
     * @mbg.generated
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.expired_time
     *
     * @param expiredTime the value for order.expired_time
     *
     * @mbg.generated
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.placed_time
     *
     * @return the value of order.placed_time
     *
     * @mbg.generated
     */
    public Date getPlacedTime() {
        return placedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.placed_time
     *
     * @param placedTime the value for order.placed_time
     *
     * @mbg.generated
     */
    public void setPlacedTime(Date placedTime) {
        this.placedTime = placedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_img
     *
     * @return the value of order.snap_img
     *
     * @mbg.generated
     */
    public String getSnapImg() {
        return snapImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_img
     *
     * @param snapImg the value for order.snap_img
     *
     * @mbg.generated
     */
    public void setSnapImg(String snapImg) {
        this.snapImg = snapImg == null ? null : snapImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_title
     *
     * @return the value of order.snap_title
     *
     * @mbg.generated
     */
    public String getSnapTitle() {
        return snapTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_title
     *
     * @param snapTitle the value for order.snap_title
     *
     * @mbg.generated
     */
    public void setSnapTitle(String snapTitle) {
        this.snapTitle = snapTitle == null ? null : snapTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_items
     *
     * @return the value of order.snap_items
     *
     * @mbg.generated
     */
    public Object getSnapItems() {
        return snapItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_items
     *
     * @param snapItems the value for order.snap_items
     *
     * @mbg.generated
     */
    public void setSnapItems(Object snapItems) {
        this.snapItems = snapItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_address
     *
     * @return the value of order.snap_address
     *
     * @mbg.generated
     */
    public Object getSnapAddress() {
        return snapAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_address
     *
     * @param snapAddress the value for order.snap_address
     *
     * @mbg.generated
     */
    public void setSnapAddress(Object snapAddress) {
        this.snapAddress = snapAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.prepay_id
     *
     * @return the value of order.prepay_id
     *
     * @mbg.generated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.prepay_id
     *
     * @param prepayId the value for order.prepay_id
     *
     * @mbg.generated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.final_total_price
     *
     * @return the value of order.final_total_price
     *
     * @mbg.generated
     */
    public BigDecimal getFinalTotalPrice() {
        return finalTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.final_total_price
     *
     * @param finalTotalPrice the value for order.final_total_price
     *
     * @mbg.generated
     */
    public void setFinalTotalPrice(BigDecimal finalTotalPrice) {
        this.finalTotalPrice = finalTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", userId=").append(userId);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", totalCount=").append(totalCount);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", expiredTime=").append(expiredTime);
        sb.append(", placedTime=").append(placedTime);
        sb.append(", snapImg=").append(snapImg);
        sb.append(", snapTitle=").append(snapTitle);
        sb.append(", snapItems=").append(snapItems);
        sb.append(", snapAddress=").append(snapAddress);
        sb.append(", prepayId=").append(prepayId);
        sb.append(", finalTotalPrice=").append(finalTotalPrice);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}