package com.guoyuhang.wx_cms.dao.model;

import java.io.Serializable;
import java.util.Date;

public class SaleExplain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.fixed
     *
     * @mbg.generated
     */
    private Byte fixed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.spu_id
     *
     * @mbg.generated
     */
    private Integer spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.index
     *
     * @mbg.generated
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.replace_id
     *
     * @mbg.generated
     */
    private Integer replaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_explain.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.id
     *
     * @return the value of sale_explain.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.id
     *
     * @param id the value for sale_explain.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.fixed
     *
     * @return the value of sale_explain.fixed
     *
     * @mbg.generated
     */
    public Byte getFixed() {
        return fixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.fixed
     *
     * @param fixed the value for sale_explain.fixed
     *
     * @mbg.generated
     */
    public void setFixed(Byte fixed) {
        this.fixed = fixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.text
     *
     * @return the value of sale_explain.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.text
     *
     * @param text the value for sale_explain.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.spu_id
     *
     * @return the value of sale_explain.spu_id
     *
     * @mbg.generated
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.spu_id
     *
     * @param spuId the value for sale_explain.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.index
     *
     * @return the value of sale_explain.index
     *
     * @mbg.generated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.index
     *
     * @param index the value for sale_explain.index
     *
     * @mbg.generated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.replace_id
     *
     * @return the value of sale_explain.replace_id
     *
     * @mbg.generated
     */
    public Integer getReplaceId() {
        return replaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.replace_id
     *
     * @param replaceId the value for sale_explain.replace_id
     *
     * @mbg.generated
     */
    public void setReplaceId(Integer replaceId) {
        this.replaceId = replaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.create_time
     *
     * @return the value of sale_explain.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.create_time
     *
     * @param createTime the value for sale_explain.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.delete_time
     *
     * @return the value of sale_explain.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.delete_time
     *
     * @param deleteTime the value for sale_explain.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_explain.update_time
     *
     * @return the value of sale_explain.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_explain.update_time
     *
     * @param updateTime the value for sale_explain.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fixed=").append(fixed);
        sb.append(", text=").append(text);
        sb.append(", spuId=").append(spuId);
        sb.append(", index=").append(index);
        sb.append(", replaceId=").append(replaceId);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}