package com.guoyuhang.wx_cms.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public SpuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("`title` is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("`title` is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("`title` =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("`title` <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("`title` >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("`title` >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("`title` <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("`title` <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("`title` like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("`title` not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("`title` in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("`title` not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("`title` between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("`title` not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNull() {
            addCriterion("`subtitle` is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNotNull() {
            addCriterion("`subtitle` is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleEqualTo(String value) {
            addCriterion("`subtitle` =", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotEqualTo(String value) {
            addCriterion("`subtitle` <>", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThan(String value) {
            addCriterion("`subtitle` >", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("`subtitle` >=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThan(String value) {
            addCriterion("`subtitle` <", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThanOrEqualTo(String value) {
            addCriterion("`subtitle` <=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLike(String value) {
            addCriterion("`subtitle` like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotLike(String value) {
            addCriterion("`subtitle` not like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleIn(List<String> values) {
            addCriterion("`subtitle` in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotIn(List<String> values) {
            addCriterion("`subtitle` not in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleBetween(String value1, String value2) {
            addCriterion("`subtitle` between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotBetween(String value1, String value2) {
            addCriterion("`subtitle` not between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("`category_id` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("`category_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("`category_id` =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("`category_id` <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("`category_id` >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`category_id` >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("`category_id` <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("`category_id` <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("`category_id` in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("`category_id` not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("`category_id` between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`category_id` not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdIsNull() {
            addCriterion("`root_category_id` is null");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdIsNotNull() {
            addCriterion("`root_category_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdEqualTo(Integer value) {
            addCriterion("`root_category_id` =", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdNotEqualTo(Integer value) {
            addCriterion("`root_category_id` <>", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdGreaterThan(Integer value) {
            addCriterion("`root_category_id` >", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`root_category_id` >=", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdLessThan(Integer value) {
            addCriterion("`root_category_id` <", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("`root_category_id` <=", value, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdIn(List<Integer> values) {
            addCriterion("`root_category_id` in", values, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdNotIn(List<Integer> values) {
            addCriterion("`root_category_id` not in", values, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("`root_category_id` between", value1, value2, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andRootCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`root_category_id` not between", value1, value2, "rootCategoryId");
            return (Criteria) this;
        }

        public Criteria andOnlineIsNull() {
            addCriterion("`online` is null");
            return (Criteria) this;
        }

        public Criteria andOnlineIsNotNull() {
            addCriterion("`online` is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineEqualTo(Byte value) {
            addCriterion("`online` =", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotEqualTo(Byte value) {
            addCriterion("`online` <>", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineGreaterThan(Byte value) {
            addCriterion("`online` >", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineGreaterThanOrEqualTo(Byte value) {
            addCriterion("`online` >=", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineLessThan(Byte value) {
            addCriterion("`online` <", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineLessThanOrEqualTo(Byte value) {
            addCriterion("`online` <=", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineIn(List<Byte> values) {
            addCriterion("`online` in", values, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotIn(List<Byte> values) {
            addCriterion("`online` not in", values, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineBetween(Byte value1, Byte value2) {
            addCriterion("`online` between", value1, value2, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotBetween(Byte value1, Byte value2) {
            addCriterion("`online` not between", value1, value2, "online");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNull() {
            addCriterion("`delete_time` is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNotNull() {
            addCriterion("`delete_time` is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeEqualTo(Date value) {
            addCriterion("`delete_time` =", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotEqualTo(Date value) {
            addCriterion("`delete_time` <>", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThan(Date value) {
            addCriterion("`delete_time` >", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`delete_time` >=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThan(Date value) {
            addCriterion("`delete_time` <", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("`delete_time` <=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIn(List<Date> values) {
            addCriterion("`delete_time` in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotIn(List<Date> values) {
            addCriterion("`delete_time` not in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeBetween(Date value1, Date value2) {
            addCriterion("`delete_time` between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("`delete_time` not between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("`price` is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("`price` is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("`price` =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("`price` <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("`price` >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("`price` >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("`price` <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("`price` <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("`price` like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("`price` not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("`price` in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("`price` not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("`price` between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("`price` not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdIsNull() {
            addCriterion("`sketch_spec_id` is null");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdIsNotNull() {
            addCriterion("`sketch_spec_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdEqualTo(Integer value) {
            addCriterion("`sketch_spec_id` =", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdNotEqualTo(Integer value) {
            addCriterion("`sketch_spec_id` <>", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdGreaterThan(Integer value) {
            addCriterion("`sketch_spec_id` >", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sketch_spec_id` >=", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdLessThan(Integer value) {
            addCriterion("`sketch_spec_id` <", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdLessThanOrEqualTo(Integer value) {
            addCriterion("`sketch_spec_id` <=", value, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdIn(List<Integer> values) {
            addCriterion("`sketch_spec_id` in", values, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdNotIn(List<Integer> values) {
            addCriterion("`sketch_spec_id` not in", values, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdBetween(Integer value1, Integer value2) {
            addCriterion("`sketch_spec_id` between", value1, value2, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andSketchSpecIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`sketch_spec_id` not between", value1, value2, "sketchSpecId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdIsNull() {
            addCriterion("`default_sku_id` is null");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdIsNotNull() {
            addCriterion("`default_sku_id` is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdEqualTo(Integer value) {
            addCriterion("`default_sku_id` =", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdNotEqualTo(Integer value) {
            addCriterion("`default_sku_id` <>", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdGreaterThan(Integer value) {
            addCriterion("`default_sku_id` >", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`default_sku_id` >=", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdLessThan(Integer value) {
            addCriterion("`default_sku_id` <", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("`default_sku_id` <=", value, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdIn(List<Integer> values) {
            addCriterion("`default_sku_id` in", values, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdNotIn(List<Integer> values) {
            addCriterion("`default_sku_id` not in", values, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("`default_sku_id` between", value1, value2, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andDefaultSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`default_sku_id` not between", value1, value2, "defaultSkuId");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("`img` is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("`img` is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("`img` =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("`img` <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("`img` >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("`img` >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("`img` <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("`img` <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("`img` like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("`img` not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("`img` in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("`img` not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("`img` between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("`img` not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNull() {
            addCriterion("`discount_price` is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNotNull() {
            addCriterion("`discount_price` is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceEqualTo(String value) {
            addCriterion("`discount_price` =", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotEqualTo(String value) {
            addCriterion("`discount_price` <>", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThan(String value) {
            addCriterion("`discount_price` >", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThanOrEqualTo(String value) {
            addCriterion("`discount_price` >=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThan(String value) {
            addCriterion("`discount_price` <", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThanOrEqualTo(String value) {
            addCriterion("`discount_price` <=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLike(String value) {
            addCriterion("`discount_price` like", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotLike(String value) {
            addCriterion("`discount_price` not like", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIn(List<String> values) {
            addCriterion("`discount_price` in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotIn(List<String> values) {
            addCriterion("`discount_price` not in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceBetween(String value1, String value2) {
            addCriterion("`discount_price` between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotBetween(String value1, String value2) {
            addCriterion("`discount_price` not between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("`tags` is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("`tags` is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("`tags` =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("`tags` <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("`tags` >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("`tags` >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("`tags` <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("`tags` <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("`tags` like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("`tags` not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("`tags` in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("`tags` not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("`tags` between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("`tags` not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andIsTestIsNull() {
            addCriterion("`is_test` is null");
            return (Criteria) this;
        }

        public Criteria andIsTestIsNotNull() {
            addCriterion("`is_test` is not null");
            return (Criteria) this;
        }

        public Criteria andIsTestEqualTo(Byte value) {
            addCriterion("`is_test` =", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotEqualTo(Byte value) {
            addCriterion("`is_test` <>", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestGreaterThan(Byte value) {
            addCriterion("`is_test` >", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestGreaterThanOrEqualTo(Byte value) {
            addCriterion("`is_test` >=", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestLessThan(Byte value) {
            addCriterion("`is_test` <", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestLessThanOrEqualTo(Byte value) {
            addCriterion("`is_test` <=", value, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestIn(List<Byte> values) {
            addCriterion("`is_test` in", values, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotIn(List<Byte> values) {
            addCriterion("`is_test` not in", values, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestBetween(Byte value1, Byte value2) {
            addCriterion("`is_test` between", value1, value2, "isTest");
            return (Criteria) this;
        }

        public Criteria andIsTestNotBetween(Byte value1, Byte value2) {
            addCriterion("`is_test` not between", value1, value2, "isTest");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgIsNull() {
            addCriterion("`spu_theme_img` is null");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgIsNotNull() {
            addCriterion("`spu_theme_img` is not null");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgEqualTo(Object value) {
            addCriterion("`spu_theme_img` =", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgNotEqualTo(Object value) {
            addCriterion("`spu_theme_img` <>", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgGreaterThan(Object value) {
            addCriterion("`spu_theme_img` >", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgGreaterThanOrEqualTo(Object value) {
            addCriterion("`spu_theme_img` >=", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgLessThan(Object value) {
            addCriterion("`spu_theme_img` <", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgLessThanOrEqualTo(Object value) {
            addCriterion("`spu_theme_img` <=", value, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgIn(List<Object> values) {
            addCriterion("`spu_theme_img` in", values, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgNotIn(List<Object> values) {
            addCriterion("`spu_theme_img` not in", values, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgBetween(Object value1, Object value2) {
            addCriterion("`spu_theme_img` between", value1, value2, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andSpuThemeImgNotBetween(Object value1, Object value2) {
            addCriterion("`spu_theme_img` not between", value1, value2, "spuThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgIsNull() {
            addCriterion("`for_theme_img` is null");
            return (Criteria) this;
        }

        public Criteria andForThemeImgIsNotNull() {
            addCriterion("`for_theme_img` is not null");
            return (Criteria) this;
        }

        public Criteria andForThemeImgEqualTo(String value) {
            addCriterion("`for_theme_img` =", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgNotEqualTo(String value) {
            addCriterion("`for_theme_img` <>", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgGreaterThan(String value) {
            addCriterion("`for_theme_img` >", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgGreaterThanOrEqualTo(String value) {
            addCriterion("`for_theme_img` >=", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgLessThan(String value) {
            addCriterion("`for_theme_img` <", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgLessThanOrEqualTo(String value) {
            addCriterion("`for_theme_img` <=", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgLike(String value) {
            addCriterion("`for_theme_img` like", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgNotLike(String value) {
            addCriterion("`for_theme_img` not like", value, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgIn(List<String> values) {
            addCriterion("`for_theme_img` in", values, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgNotIn(List<String> values) {
            addCriterion("`for_theme_img` not in", values, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgBetween(String value1, String value2) {
            addCriterion("`for_theme_img` between", value1, value2, "forThemeImg");
            return (Criteria) this;
        }

        public Criteria andForThemeImgNotBetween(String value1, String value2) {
            addCriterion("`for_theme_img` not between", value1, value2, "forThemeImg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spu
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spu
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}