package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.ActivitySpu;
import com.guoyuhang.wx_cms.dao.model.ActivitySpuExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ActivitySpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivitySpuSqlProvider.class, method="countByExample")
    long countByExample(ActivitySpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @DeleteProvider(type= ActivitySpuSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActivitySpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from activity_spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into activity_spu (`activity_id`, `spu_id`, ",
        "`participation`)",
        "values (#{activityId,jdbcType=INTEGER}, #{spuId,jdbcType=INTEGER}, ",
        "#{participation,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ActivitySpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @InsertProvider(type= ActivitySpuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ActivitySpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivitySpuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="participation", property="participation", jdbcType=JdbcType.TINYINT)
    })
    List<ActivitySpu> selectByExample(ActivitySpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `activity_id`, `spu_id`, `participation`",
        "from activity_spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="participation", property="participation", jdbcType=JdbcType.TINYINT)
    })
    ActivitySpu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivitySpuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ActivitySpu record, @Param("example") ActivitySpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivitySpuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ActivitySpu record, @Param("example") ActivitySpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivitySpuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ActivitySpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_spu
     *
     * @mbg.generated
     */
    @Update({
        "update activity_spu",
        "set `activity_id` = #{activityId,jdbcType=INTEGER},",
          "`spu_id` = #{spuId,jdbcType=INTEGER},",
          "`participation` = #{participation,jdbcType=TINYINT}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivitySpu record);
}