package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.ActivityCategory;
import com.guoyuhang.wx_cms.dao.model.ActivityCategoryExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ActivityCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivityCategorySqlProvider.class, method="countByExample")
    long countByExample(ActivityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @DeleteProvider(type= ActivityCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(ActivityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from activity_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into activity_category (`category_id`, `activity_id`)",
        "values (#{categoryId,jdbcType=INTEGER}, #{activityId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @InsertProvider(type= ActivityCategorySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivityCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER)
    })
    List<ActivityCategory> selectByExample(ActivityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `category_id`, `activity_id`",
        "from activity_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER)
    })
    ActivityCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ActivityCategory record, @Param("example") ActivityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ActivityCategory record, @Param("example") ActivityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbg.generated
     */
    @Update({
        "update activity_category",
        "set `category_id` = #{categoryId,jdbcType=INTEGER},",
          "`activity_id` = #{activityId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivityCategory record);
}