package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.ActivityCoupon;
import com.guoyuhang.wx_cms.dao.model.ActivityCouponExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ActivityCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivityCouponSqlProvider.class, method="countByExample")
    long countByExample(ActivityCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type= ActivityCouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActivityCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from activity_coupon",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into activity_coupon (`coupon_id`, `activity_id`)",
        "values (#{couponId,jdbcType=INTEGER}, #{activityId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ActivityCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type= ActivityCouponSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ActivityCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type= ActivityCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER)
    })
    List<ActivityCoupon> selectByExample(ActivityCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `coupon_id`, `activity_id`",
        "from activity_coupon",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.INTEGER)
    })
    ActivityCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ActivityCoupon record, @Param("example") ActivityCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ActivityCoupon record, @Param("example") ActivityCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= ActivityCouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ActivityCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update activity_coupon",
        "set `coupon_id` = #{couponId,jdbcType=INTEGER},",
          "`activity_id` = #{activityId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivityCoupon record);
}