package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.CouponType;
import com.guoyuhang.wx_cms.dao.model.CouponTypeExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CouponTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponTypeSqlProvider.class, method="countByExample")
    long countByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CouponTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @Delete({
        "delete from coupon_type",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @Insert({
        "insert into coupon_type (`name`, `code`, ",
        "`description`, `create_time`, ",
        "`update_time`, `delete_time`)",
        "values (#{name,jdbcType=VARCHAR}, #{code,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @InsertProvider(type=CouponTypeSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.INTEGER),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CouponType> selectByExample(CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `name`, `code`, `description`, `create_time`, `update_time`, `delete_time`",
        "from coupon_type",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.INTEGER),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    CouponType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CouponType record, @Param("example") CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CouponType record, @Param("example") CouponTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CouponType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_type
     *
     * @mbg.generated
     */
    @Update({
        "update coupon_type",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "`code` = #{code,jdbcType=INTEGER},",
          "`description` = #{description,jdbcType=VARCHAR},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CouponType record);
}