package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.CouponCategory;
import com.guoyuhang.wx_cms.dao.model.CouponCategoryExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CouponCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponCategorySqlProvider.class, method="countByExample")
    long countByExample(CouponCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CouponCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(CouponCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from coupon_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into coupon_category (`category_id`, `coupon_id`)",
        "values (#{categoryId,jdbcType=INTEGER}, #{couponId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CouponCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @InsertProvider(type=CouponCategorySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CouponCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER)
    })
    List<CouponCategory> selectByExample(CouponCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `category_id`, `coupon_id`",
        "from coupon_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER)
    })
    CouponCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CouponCategory record, @Param("example") CouponCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CouponCategory record, @Param("example") CouponCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CouponCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_category
     *
     * @mbg.generated
     */
    @Update({
        "update coupon_category",
        "set `category_id` = #{categoryId,jdbcType=INTEGER},",
          "`coupon_id` = #{couponId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CouponCategory record);
}