package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.CouponTemplate;
import com.guoyuhang.wx_cms.dao.model.CouponTemplateExample;
import com.guoyuhang.wx_cms.dao.model.CouponTemplateExample.Criteria;
import com.guoyuhang.wx_cms.dao.model.CouponTemplateExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class CouponTemplateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String countByExample(CouponTemplateExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("coupon_template");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String deleteByExample(CouponTemplateExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("coupon_template");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String insertSelective(CouponTemplate record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("coupon_template");
        
        if (record.getTitle() != null) {
            sql.VALUES("`title`", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("`description`", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getFullMoney() != null) {
            sql.VALUES("`full_money`", "#{fullMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getMinus() != null) {
            sql.VALUES("`minus`", "#{minus,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscount() != null) {
            sql.VALUES("`discount`", "#{discount,jdbcType=DECIMAL}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("`type`", "#{type,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("`update_time`", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.VALUES("`delete_time`", "#{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String selectByExample(CouponTemplateExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`title`");
        sql.SELECT("`description`");
        sql.SELECT("`full_money`");
        sql.SELECT("`minus`");
        sql.SELECT("`discount`");
        sql.SELECT("`type`");
        sql.SELECT("`create_time`");
        sql.SELECT("`update_time`");
        sql.SELECT("`delete_time`");
        sql.FROM("coupon_template");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CouponTemplate record = (CouponTemplate) parameter.get("record");
        CouponTemplateExample example = (CouponTemplateExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("coupon_template");
        
        if (record.getId() != null) {
            sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("`description` = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getFullMoney() != null) {
            sql.SET("`full_money` = #{record.fullMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getMinus() != null) {
            sql.SET("`minus` = #{record.minus,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscount() != null) {
            sql.SET("`discount` = #{record.discount,jdbcType=DECIMAL}");
        }
        
        if (record.getType() != null) {
            sql.SET("`type` = #{record.type,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("coupon_template");
        
        sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        sql.SET("`description` = #{record.description,jdbcType=VARCHAR}");
        sql.SET("`full_money` = #{record.fullMoney,jdbcType=DECIMAL}");
        sql.SET("`minus` = #{record.minus,jdbcType=DECIMAL}");
        sql.SET("`discount` = #{record.discount,jdbcType=DECIMAL}");
        sql.SET("`type` = #{record.type,jdbcType=SMALLINT}");
        sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        
        CouponTemplateExample example = (CouponTemplateExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(CouponTemplate record) {
        SQL sql = new SQL();
        sql.UPDATE("coupon_template");
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("`description` = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getFullMoney() != null) {
            sql.SET("`full_money` = #{fullMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getMinus() != null) {
            sql.SET("`minus` = #{minus,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscount() != null) {
            sql.SET("`discount` = #{discount,jdbcType=DECIMAL}");
        }
        
        if (record.getType() != null) {
            sql.SET("`type` = #{type,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_template
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CouponTemplateExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}