package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.GridCategory;
import com.guoyuhang.wx_cms.dao.model.GridCategoryExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface GridCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @SelectProvider(type= GridCategorySqlProvider.class, method="countByExample")
    long countByExample(GridCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @DeleteProvider(type= GridCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(GridCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from grid_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into grid_category (`title`, `img`, ",
        "`name`, `create_time`, ",
        "`update_time`, `delete_time`, ",
        "`category_id`, `root_category_id`)",
        "values (#{title,jdbcType=VARCHAR}, #{img,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP}, ",
        "#{categoryId,jdbcType=INTEGER}, #{rootCategoryId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(GridCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @InsertProvider(type= GridCategorySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(GridCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @SelectProvider(type= GridCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER)
    })
    List<GridCategory> selectByExample(GridCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `title`, `img`, `name`, `create_time`, `update_time`, `delete_time`, `category_id`, ",
        "`root_category_id`",
        "from grid_category",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER)
    })
    GridCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= GridCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GridCategory record, @Param("example") GridCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= GridCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GridCategory record, @Param("example") GridCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type= GridCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GridCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_category
     *
     * @mbg.generated
     */
    @Update({
        "update grid_category",
        "set `title` = #{title,jdbcType=VARCHAR},",
          "`img` = #{img,jdbcType=VARCHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP},",
          "`category_id` = #{categoryId,jdbcType=INTEGER},",
          "`root_category_id` = #{rootCategoryId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GridCategory record);
}