package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.Order;
import com.guoyuhang.wx_cms.dao.model.OrderExample;
import com.guoyuhang.wx_cms.dao.model.OrderExample.Criteria;
import com.guoyuhang.wx_cms.dao.model.OrderExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class OrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String countByExample(OrderExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String deleteByExample(OrderExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String insertSelective(Order record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order");
        
        if (record.getOrderNo() != null) {
            sql.VALUES("`order_no`", "#{orderNo,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("`user_id`", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getTotalPrice() != null) {
            sql.VALUES("`total_price`", "#{totalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalCount() != null) {
            sql.VALUES("`total_count`", "#{totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.VALUES("`delete_time`", "#{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("`update_time`", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getExpiredTime() != null) {
            sql.VALUES("`expired_time`", "#{expiredTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlacedTime() != null) {
            sql.VALUES("`placed_time`", "#{placedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSnapImg() != null) {
            sql.VALUES("`snap_img`", "#{snapImg,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapTitle() != null) {
            sql.VALUES("`snap_title`", "#{snapTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapItems() != null) {
            sql.VALUES("`snap_items`", "#{snapItems,jdbcType=OTHER}");
        }
        
        if (record.getSnapAddress() != null) {
            sql.VALUES("`snap_address`", "#{snapAddress,jdbcType=OTHER}");
        }
        
        if (record.getPrepayId() != null) {
            sql.VALUES("`prepay_id`", "#{prepayId,jdbcType=VARCHAR}");
        }
        
        if (record.getFinalTotalPrice() != null) {
            sql.VALUES("`final_total_price`", "#{finalTotalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("`status`", "#{status,jdbcType=TINYINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String selectByExample(OrderExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`order_no`");
        sql.SELECT("`user_id`");
        sql.SELECT("`total_price`");
        sql.SELECT("`total_count`");
        sql.SELECT("`create_time`");
        sql.SELECT("`delete_time`");
        sql.SELECT("`update_time`");
        sql.SELECT("`expired_time`");
        sql.SELECT("`placed_time`");
        sql.SELECT("`snap_img`");
        sql.SELECT("`snap_title`");
        sql.SELECT("`snap_items`");
        sql.SELECT("`snap_address`");
        sql.SELECT("`prepay_id`");
        sql.SELECT("`final_total_price`");
        sql.SELECT("`status`");
        sql.FROM("order");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Order record = (Order) parameter.get("record");
        OrderExample example = (OrderExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("order");
        
        if (record.getId() != null) {
            sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getOrderNo() != null) {
            sql.SET("`order_no` = #{record.orderNo,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("`user_id` = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getTotalPrice() != null) {
            sql.SET("`total_price` = #{record.totalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalCount() != null) {
            sql.SET("`total_count` = #{record.totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getExpiredTime() != null) {
            sql.SET("`expired_time` = #{record.expiredTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlacedTime() != null) {
            sql.SET("`placed_time` = #{record.placedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSnapImg() != null) {
            sql.SET("`snap_img` = #{record.snapImg,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapTitle() != null) {
            sql.SET("`snap_title` = #{record.snapTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapItems() != null) {
            sql.SET("`snap_items` = #{record.snapItems,jdbcType=OTHER}");
        }
        
        if (record.getSnapAddress() != null) {
            sql.SET("`snap_address` = #{record.snapAddress,jdbcType=OTHER}");
        }
        
        if (record.getPrepayId() != null) {
            sql.SET("`prepay_id` = #{record.prepayId,jdbcType=VARCHAR}");
        }
        
        if (record.getFinalTotalPrice() != null) {
            sql.SET("`final_total_price` = #{record.finalTotalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("`status` = #{record.status,jdbcType=TINYINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("order");
        
        sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        sql.SET("`order_no` = #{record.orderNo,jdbcType=VARCHAR}");
        sql.SET("`user_id` = #{record.userId,jdbcType=INTEGER}");
        sql.SET("`total_price` = #{record.totalPrice,jdbcType=DECIMAL}");
        sql.SET("`total_count` = #{record.totalCount,jdbcType=INTEGER}");
        sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("`expired_time` = #{record.expiredTime,jdbcType=TIMESTAMP}");
        sql.SET("`placed_time` = #{record.placedTime,jdbcType=TIMESTAMP}");
        sql.SET("`snap_img` = #{record.snapImg,jdbcType=VARCHAR}");
        sql.SET("`snap_title` = #{record.snapTitle,jdbcType=VARCHAR}");
        sql.SET("`snap_items` = #{record.snapItems,jdbcType=OTHER}");
        sql.SET("`snap_address` = #{record.snapAddress,jdbcType=OTHER}");
        sql.SET("`prepay_id` = #{record.prepayId,jdbcType=VARCHAR}");
        sql.SET("`final_total_price` = #{record.finalTotalPrice,jdbcType=DECIMAL}");
        sql.SET("`status` = #{record.status,jdbcType=TINYINT}");
        
        OrderExample example = (OrderExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Order record) {
        SQL sql = new SQL();
        sql.UPDATE("order");
        
        if (record.getOrderNo() != null) {
            sql.SET("`order_no` = #{orderNo,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("`user_id` = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getTotalPrice() != null) {
            sql.SET("`total_price` = #{totalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalCount() != null) {
            sql.SET("`total_count` = #{totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getExpiredTime() != null) {
            sql.SET("`expired_time` = #{expiredTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlacedTime() != null) {
            sql.SET("`placed_time` = #{placedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSnapImg() != null) {
            sql.SET("`snap_img` = #{snapImg,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapTitle() != null) {
            sql.SET("`snap_title` = #{snapTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getSnapItems() != null) {
            sql.SET("`snap_items` = #{snapItems,jdbcType=OTHER}");
        }
        
        if (record.getSnapAddress() != null) {
            sql.SET("`snap_address` = #{snapAddress,jdbcType=OTHER}");
        }
        
        if (record.getPrepayId() != null) {
            sql.SET("`prepay_id` = #{prepayId,jdbcType=VARCHAR}");
        }
        
        if (record.getFinalTotalPrice() != null) {
            sql.SET("`final_total_price` = #{finalTotalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("`status` = #{status,jdbcType=TINYINT}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, OrderExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}