package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SaleExplain;
import com.guoyuhang.wx_cms.dao.model.SaleExplainExample;
import com.guoyuhang.wx_cms.dao.model.SaleExplainExample.Criteria;
import com.guoyuhang.wx_cms.dao.model.SaleExplainExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class SaleExplainSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String countByExample(SaleExplainExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("sale_explain");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String deleteByExample(SaleExplainExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("sale_explain");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String insertSelective(SaleExplain record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sale_explain");
        
        if (record.getFixed() != null) {
            sql.VALUES("`fixed`", "#{fixed,jdbcType=TINYINT}");
        }
        
        if (record.getText() != null) {
            sql.VALUES("`text`", "#{text,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.VALUES("`spu_id`", "#{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getIndex() != null) {
            sql.VALUES("`index`", "#{index,jdbcType=INTEGER}");
        }
        
        if (record.getReplaceId() != null) {
            sql.VALUES("`replace_id`", "#{replaceId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.VALUES("`delete_time`", "#{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("`update_time`", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String selectByExample(SaleExplainExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`fixed`");
        sql.SELECT("`text`");
        sql.SELECT("`spu_id`");
        sql.SELECT("`index`");
        sql.SELECT("`replace_id`");
        sql.SELECT("`create_time`");
        sql.SELECT("`delete_time`");
        sql.SELECT("`update_time`");
        sql.FROM("sale_explain");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SaleExplain record = (SaleExplain) parameter.get("record");
        SaleExplainExample example = (SaleExplainExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("sale_explain");
        
        if (record.getId() != null) {
            sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getFixed() != null) {
            sql.SET("`fixed` = #{record.fixed,jdbcType=TINYINT}");
        }
        
        if (record.getText() != null) {
            sql.SET("`text` = #{record.text,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.SET("`spu_id` = #{record.spuId,jdbcType=INTEGER}");
        }
        
        if (record.getIndex() != null) {
            sql.SET("`index` = #{record.index,jdbcType=INTEGER}");
        }
        
        if (record.getReplaceId() != null) {
            sql.SET("`replace_id` = #{record.replaceId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("sale_explain");
        
        sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        sql.SET("`fixed` = #{record.fixed,jdbcType=TINYINT}");
        sql.SET("`text` = #{record.text,jdbcType=VARCHAR}");
        sql.SET("`spu_id` = #{record.spuId,jdbcType=INTEGER}");
        sql.SET("`index` = #{record.index,jdbcType=INTEGER}");
        sql.SET("`replace_id` = #{record.replaceId,jdbcType=INTEGER}");
        sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        SaleExplainExample example = (SaleExplainExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(SaleExplain record) {
        SQL sql = new SQL();
        sql.UPDATE("sale_explain");
        
        if (record.getFixed() != null) {
            sql.SET("`fixed` = #{fixed,jdbcType=TINYINT}");
        }
        
        if (record.getText() != null) {
            sql.SET("`text` = #{text,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.SET("`spu_id` = #{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getIndex() != null) {
            sql.SET("`index` = #{index,jdbcType=INTEGER}");
        }
        
        if (record.getReplaceId() != null) {
            sql.SET("`replace_id` = #{replaceId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, SaleExplainExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}