package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SaleExplain;
import com.guoyuhang.wx_cms.dao.model.SaleExplainExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SaleExplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @SelectProvider(type=SaleExplainSqlProvider.class, method="countByExample")
    long countByExample(SaleExplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SaleExplainSqlProvider.class, method="deleteByExample")
    int deleteByExample(SaleExplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sale_explain",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sale_explain (`fixed`, `text`, ",
        "`spu_id`, `index`, `replace_id`, ",
        "`create_time`, `delete_time`, ",
        "`update_time`)",
        "values (#{fixed,jdbcType=TINYINT}, #{text,jdbcType=VARCHAR}, ",
        "#{spuId,jdbcType=INTEGER}, #{index,jdbcType=INTEGER}, #{replaceId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SaleExplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @InsertProvider(type=SaleExplainSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SaleExplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @SelectProvider(type=SaleExplainSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fixed", property="fixed", jdbcType=JdbcType.TINYINT),
        @Result(column="text", property="text", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="index", property="index", jdbcType=JdbcType.INTEGER),
        @Result(column="replace_id", property="replaceId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SaleExplain> selectByExample(SaleExplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `fixed`, `text`, `spu_id`, `index`, `replace_id`, `create_time`, `delete_time`, ",
        "`update_time`",
        "from sale_explain",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fixed", property="fixed", jdbcType=JdbcType.TINYINT),
        @Result(column="text", property="text", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="index", property="index", jdbcType=JdbcType.INTEGER),
        @Result(column="replace_id", property="replaceId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SaleExplain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SaleExplainSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SaleExplain record, @Param("example") SaleExplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SaleExplainSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SaleExplain record, @Param("example") SaleExplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SaleExplainSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SaleExplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_explain
     *
     * @mbg.generated
     */
    @Update({
        "update sale_explain",
        "set `fixed` = #{fixed,jdbcType=TINYINT},",
          "`text` = #{text,jdbcType=VARCHAR},",
          "`spu_id` = #{spuId,jdbcType=INTEGER},",
          "`index` = #{index,jdbcType=INTEGER},",
          "`replace_id` = #{replaceId,jdbcType=INTEGER},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SaleExplain record);
}