package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.Sku;
import com.guoyuhang.wx_cms.dao.model.SkuExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @SelectProvider(type= SkuSqlProvider.class, method="countByExample")
    long countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @DeleteProvider(type= SkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sku",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sku (`price`, `discount_price`, ",
        "`online`, `img`, `title`, ",
        "`spu_id`, `create_time`, ",
        "`update_time`, `delete_time`, ",
        "`specs`, `code`, `stock`, ",
        "`category_id`, `root_category_id`)",
        "values (#{price,jdbcType=DECIMAL}, #{discountPrice,jdbcType=DECIMAL}, ",
        "#{online,jdbcType=TINYINT}, #{img,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{spuId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP}, ",
        "#{specs,jdbcType=OTHER}, #{code,jdbcType=VARCHAR}, #{stock,jdbcType=INTEGER}, ",
        "#{categoryId,jdbcType=INTEGER}, #{rootCategoryId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @InsertProvider(type= SkuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @SelectProvider(type= SkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="discount_price", property="discountPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="online", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="specs", property="specs", jdbcType=JdbcType.OTHER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER)
    })
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `price`, `discount_price`, `online`, `img`, `title`, `spu_id`, `create_time`, ",
        "`update_time`, `delete_time`, `specs`, `code`, `stock`, `category_id`, `root_category_id`",
        "from sku",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="discount_price", property="discountPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="online", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="specs", property="specs", jdbcType=JdbcType.OTHER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER)
    })
    Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SkuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Update({
        "update sku",
        "set `price` = #{price,jdbcType=DECIMAL},",
          "`discount_price` = #{discountPrice,jdbcType=DECIMAL},",
          "`online` = #{online,jdbcType=TINYINT},",
          "`img` = #{img,jdbcType=VARCHAR},",
          "`title` = #{title,jdbcType=VARCHAR},",
          "`spu_id` = #{spuId,jdbcType=INTEGER},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP},",
          "`specs` = #{specs,jdbcType=OTHER},",
          "`code` = #{code,jdbcType=VARCHAR},",
          "`stock` = #{stock,jdbcType=INTEGER},",
          "`category_id` = #{categoryId,jdbcType=INTEGER},",
          "`root_category_id` = #{rootCategoryId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sku record);
}