package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SkuSpec;
import com.guoyuhang.wx_cms.dao.model.SkuSpecExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SkuSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuSpecSqlProvider.class, method="countByExample")
    long countByExample(SkuSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SkuSpecSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkuSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sku_spec",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sku_spec (`spu_id`, `sku_id`, ",
        "`key_id`, `value_id`)",
        "values (#{spuId,jdbcType=INTEGER}, #{skuId,jdbcType=INTEGER}, ",
        "#{keyId,jdbcType=INTEGER}, #{valueId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @InsertProvider(type=SkuSpecSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuSpecSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.INTEGER),
        @Result(column="value_id", property="valueId", jdbcType=JdbcType.INTEGER)
    })
    List<SkuSpec> selectByExample(SkuSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `spu_id`, `sku_id`, `key_id`, `value_id`",
        "from sku_spec",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.INTEGER),
        @Result(column="value_id", property="valueId", jdbcType=JdbcType.INTEGER)
    })
    SkuSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuSpecSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SkuSpec record, @Param("example") SkuSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuSpecSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SkuSpec record, @Param("example") SkuSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuSpecSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SkuSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_spec
     *
     * @mbg.generated
     */
    @Update({
        "update sku_spec",
        "set `spu_id` = #{spuId,jdbcType=INTEGER},",
          "`sku_id` = #{skuId,jdbcType=INTEGER},",
          "`key_id` = #{keyId,jdbcType=INTEGER},",
          "`value_id` = #{valueId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SkuSpec record);
}