package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.Sku;
import com.guoyuhang.wx_cms.dao.model.SkuExample;
import com.guoyuhang.wx_cms.dao.model.SkuExample.Criteria;
import com.guoyuhang.wx_cms.dao.model.SkuExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class SkuSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String countByExample(SkuExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("sku");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String deleteByExample(SkuExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("sku");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String insertSelective(Sku record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sku");
        
        if (record.getPrice() != null) {
            sql.VALUES("`price`", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.VALUES("`discount_price`", "#{discountPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOnline() != null) {
            sql.VALUES("`online`", "#{online,jdbcType=TINYINT}");
        }
        
        if (record.getImg() != null) {
            sql.VALUES("`img`", "#{img,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("`title`", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.VALUES("`spu_id`", "#{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("`update_time`", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.VALUES("`delete_time`", "#{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpecs() != null) {
            sql.VALUES("`specs`", "#{specs,jdbcType=OTHER}");
        }
        
        if (record.getCode() != null) {
            sql.VALUES("`code`", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getStock() != null) {
            sql.VALUES("`stock`", "#{stock,jdbcType=INTEGER}");
        }
        
        if (record.getCategoryId() != null) {
            sql.VALUES("`category_id`", "#{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.VALUES("`root_category_id`", "#{rootCategoryId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String selectByExample(SkuExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`price`");
        sql.SELECT("`discount_price`");
        sql.SELECT("`online`");
        sql.SELECT("`img`");
        sql.SELECT("`title`");
        sql.SELECT("`spu_id`");
        sql.SELECT("`create_time`");
        sql.SELECT("`update_time`");
        sql.SELECT("`delete_time`");
        sql.SELECT("`specs`");
        sql.SELECT("`code`");
        sql.SELECT("`stock`");
        sql.SELECT("`category_id`");
        sql.SELECT("`root_category_id`");
        sql.FROM("sku");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Sku record = (Sku) parameter.get("record");
        SkuExample example = (SkuExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("sku");
        
        if (record.getId() != null) {
            sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("`price` = #{record.price,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{record.discountPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOnline() != null) {
            sql.SET("`online` = #{record.online,jdbcType=TINYINT}");
        }
        
        if (record.getImg() != null) {
            sql.SET("`img` = #{record.img,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.SET("`spu_id` = #{record.spuId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpecs() != null) {
            sql.SET("`specs` = #{record.specs,jdbcType=OTHER}");
        }
        
        if (record.getCode() != null) {
            sql.SET("`code` = #{record.code,jdbcType=VARCHAR}");
        }
        
        if (record.getStock() != null) {
            sql.SET("`stock` = #{record.stock,jdbcType=INTEGER}");
        }
        
        if (record.getCategoryId() != null) {
            sql.SET("`category_id` = #{record.categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.SET("`root_category_id` = #{record.rootCategoryId,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("sku");
        
        sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        sql.SET("`price` = #{record.price,jdbcType=DECIMAL}");
        sql.SET("`discount_price` = #{record.discountPrice,jdbcType=DECIMAL}");
        sql.SET("`online` = #{record.online,jdbcType=TINYINT}");
        sql.SET("`img` = #{record.img,jdbcType=VARCHAR}");
        sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        sql.SET("`spu_id` = #{record.spuId,jdbcType=INTEGER}");
        sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        sql.SET("`specs` = #{record.specs,jdbcType=OTHER}");
        sql.SET("`code` = #{record.code,jdbcType=VARCHAR}");
        sql.SET("`stock` = #{record.stock,jdbcType=INTEGER}");
        sql.SET("`category_id` = #{record.categoryId,jdbcType=INTEGER}");
        sql.SET("`root_category_id` = #{record.rootCategoryId,jdbcType=INTEGER}");
        
        SkuExample example = (SkuExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Sku record) {
        SQL sql = new SQL();
        sql.UPDATE("sku");
        
        if (record.getPrice() != null) {
            sql.SET("`price` = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{discountPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOnline() != null) {
            sql.SET("`online` = #{online,jdbcType=TINYINT}");
        }
        
        if (record.getImg() != null) {
            sql.SET("`img` = #{img,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getSpuId() != null) {
            sql.SET("`spu_id` = #{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpecs() != null) {
            sql.SET("`specs` = #{specs,jdbcType=OTHER}");
        }
        
        if (record.getCode() != null) {
            sql.SET("`code` = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getStock() != null) {
            sql.SET("`stock` = #{stock,jdbcType=INTEGER}");
        }
        
        if (record.getCategoryId() != null) {
            sql.SET("`category_id` = #{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.SET("`root_category_id` = #{rootCategoryId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, SkuExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}