package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SpuDetailImg;
import com.guoyuhang.wx_cms.dao.model.SpuDetailImgExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SpuDetailImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuDetailImgSqlProvider.class, method="countByExample")
    long countByExample(SpuDetailImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SpuDetailImgSqlProvider.class, method="deleteByExample")
    int deleteByExample(SpuDetailImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_detail_img",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_detail_img (`img`, `spu_id`, ",
        "`index`, `create_time`, ",
        "`update_time`, `delete_time`)",
        "values (#{img,jdbcType=VARCHAR}, #{spuId,jdbcType=INTEGER}, ",
        "#{index,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SpuDetailImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @InsertProvider(type=SpuDetailImgSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SpuDetailImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuDetailImgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="index", property="index", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SpuDetailImg> selectByExample(SpuDetailImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `img`, `spu_id`, `index`, `create_time`, `update_time`, `delete_time`",
        "from spu_detail_img",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="index", property="index", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SpuDetailImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuDetailImgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SpuDetailImg record, @Param("example") SpuDetailImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuDetailImgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SpuDetailImg record, @Param("example") SpuDetailImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuDetailImgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SpuDetailImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_detail_img
     *
     * @mbg.generated
     */
    @Update({
        "update spu_detail_img",
        "set `img` = #{img,jdbcType=VARCHAR},",
          "`spu_id` = #{spuId,jdbcType=INTEGER},",
          "`index` = #{index,jdbcType=INTEGER},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuDetailImg record);
}