package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SpuImg;
import com.guoyuhang.wx_cms.dao.model.SpuImgExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SpuImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuImgSqlProvider.class, method="countByExample")
    long countByExample(SpuImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SpuImgSqlProvider.class, method="deleteByExample")
    int deleteByExample(SpuImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_img",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_img (`img`, `spu_id`, ",
        "`delete_time`, `update_time`, ",
        "`create_time`)",
        "values (#{img,jdbcType=VARCHAR}, #{spuId,jdbcType=INTEGER}, ",
        "#{deleteTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SpuImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @InsertProvider(type=SpuImgSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SpuImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuImgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SpuImg> selectByExample(SpuImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `img`, `spu_id`, `delete_time`, `update_time`, `create_time`",
        "from spu_img",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SpuImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuImgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SpuImg record, @Param("example") SpuImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuImgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SpuImg record, @Param("example") SpuImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuImgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SpuImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_img
     *
     * @mbg.generated
     */
    @Update({
        "update spu_img",
        "set `img` = #{img,jdbcType=VARCHAR},",
          "`spu_id` = #{spuId,jdbcType=INTEGER},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuImg record);
}