package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SpuKey;
import com.guoyuhang.wx_cms.dao.model.SpuKeyExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SpuKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @SelectProvider(type= SpuKeySqlProvider.class, method="countByExample")
    long countByExample(SpuKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @DeleteProvider(type= SpuKeySqlProvider.class, method="deleteByExample")
    int deleteByExample(SpuKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_key",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_key (`spu_id`, `spec_key_id`)",
        "values (#{spuId,jdbcType=INTEGER}, #{specKeyId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SpuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @InsertProvider(type= SpuKeySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SpuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @SelectProvider(type= SpuKeySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="spec_key_id", property="specKeyId", jdbcType=JdbcType.INTEGER)
    })
    List<SpuKey> selectByExample(SpuKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `spu_id`, `spec_key_id`",
        "from spu_key",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="spec_key_id", property="specKeyId", jdbcType=JdbcType.INTEGER)
    })
    SpuKey selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SpuKeySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SpuKey record, @Param("example") SpuKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SpuKeySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SpuKey record, @Param("example") SpuKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type= SpuKeySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SpuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_key
     *
     * @mbg.generated
     */
    @Update({
        "update spu_key",
        "set `spu_id` = #{spuId,jdbcType=INTEGER},",
          "`spec_key_id` = #{specKeyId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuKey record);
}