package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.Spu;
import com.guoyuhang.wx_cms.dao.model.SpuExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuSqlProvider.class, method="countByExample")
    long countByExample(SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SpuSqlProvider.class, method="deleteByExample")
    int deleteByExample(SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu (`title`, `subtitle`, ",
        "`category_id`, `root_category_id`, ",
        "`online`, `create_time`, ",
        "`update_time`, `delete_time`, ",
        "`price`, `sketch_spec_id`, ",
        "`default_sku_id`, `img`, ",
        "`discount_price`, `description`, ",
        "`tags`, `is_test`, `spu_theme_img`, ",
        "`for_theme_img`)",
        "values (#{title,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{categoryId,jdbcType=INTEGER}, #{rootCategoryId,jdbcType=INTEGER}, ",
        "#{online,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleteTime,jdbcType=TIMESTAMP}, ",
        "#{price,jdbcType=VARCHAR}, #{sketchSpecId,jdbcType=INTEGER}, ",
        "#{defaultSkuId,jdbcType=INTEGER}, #{img,jdbcType=VARCHAR}, ",
        "#{discountPrice,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{tags,jdbcType=VARCHAR}, #{isTest,jdbcType=TINYINT}, #{spuThemeImg,jdbcType=OTHER}, ",
        "#{forThemeImg,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @InsertProvider(type=SpuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="subtitle", property="subtitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="online", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR),
        @Result(column="sketch_spec_id", property="sketchSpecId", jdbcType=JdbcType.INTEGER),
        @Result(column="default_sku_id", property="defaultSkuId", jdbcType=JdbcType.INTEGER),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="discount_price", property="discountPrice", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="tags", property="tags", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_test", property="isTest", jdbcType=JdbcType.TINYINT),
        @Result(column="spu_theme_img", property="spuThemeImg", jdbcType=JdbcType.OTHER),
        @Result(column="for_theme_img", property="forThemeImg", jdbcType=JdbcType.VARCHAR)
    })
    List<Spu> selectByExample(SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `title`, `subtitle`, `category_id`, `root_category_id`, `online`, `create_time`, ",
        "`update_time`, `delete_time`, `price`, `sketch_spec_id`, `default_sku_id`, `img`, ",
        "`discount_price`, `description`, `tags`, `is_test`, `spu_theme_img`, `for_theme_img`",
        "from spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="subtitle", property="subtitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="root_category_id", property="rootCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="online", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR),
        @Result(column="sketch_spec_id", property="sketchSpecId", jdbcType=JdbcType.INTEGER),
        @Result(column="default_sku_id", property="defaultSkuId", jdbcType=JdbcType.INTEGER),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="discount_price", property="discountPrice", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="tags", property="tags", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_test", property="isTest", jdbcType=JdbcType.TINYINT),
        @Result(column="spu_theme_img", property="spuThemeImg", jdbcType=JdbcType.OTHER),
        @Result(column="for_theme_img", property="forThemeImg", jdbcType=JdbcType.VARCHAR)
    })
    Spu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Spu record, @Param("example") SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Spu record, @Param("example") SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Update({
        "update spu",
        "set `title` = #{title,jdbcType=VARCHAR},",
          "`subtitle` = #{subtitle,jdbcType=VARCHAR},",
          "`category_id` = #{categoryId,jdbcType=INTEGER},",
          "`root_category_id` = #{rootCategoryId,jdbcType=INTEGER},",
          "`online` = #{online,jdbcType=TINYINT},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`delete_time` = #{deleteTime,jdbcType=TIMESTAMP},",
          "`price` = #{price,jdbcType=VARCHAR},",
          "`sketch_spec_id` = #{sketchSpecId,jdbcType=INTEGER},",
          "`default_sku_id` = #{defaultSkuId,jdbcType=INTEGER},",
          "`img` = #{img,jdbcType=VARCHAR},",
          "`discount_price` = #{discountPrice,jdbcType=VARCHAR},",
          "`description` = #{description,jdbcType=VARCHAR},",
          "`tags` = #{tags,jdbcType=VARCHAR},",
          "`is_test` = #{isTest,jdbcType=TINYINT},",
          "`spu_theme_img` = #{spuThemeImg,jdbcType=OTHER},",
          "`for_theme_img` = #{forThemeImg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Spu record);
}