package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.Spu;
import com.guoyuhang.wx_cms.dao.model.SpuExample;
import com.guoyuhang.wx_cms.dao.model.SpuExample.Criteria;
import com.guoyuhang.wx_cms.dao.model.SpuExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class SpuSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String countByExample(SpuExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("spu");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String deleteByExample(SpuExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("spu");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String insertSelective(Spu record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("spu");
        
        if (record.getTitle() != null) {
            sql.VALUES("`title`", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getSubtitle() != null) {
            sql.VALUES("`subtitle`", "#{subtitle,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryId() != null) {
            sql.VALUES("`category_id`", "#{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.VALUES("`root_category_id`", "#{rootCategoryId,jdbcType=INTEGER}");
        }
        
        if (record.getOnline() != null) {
            sql.VALUES("`online`", "#{online,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("`update_time`", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.VALUES("`delete_time`", "#{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("`price`", "#{price,jdbcType=VARCHAR}");
        }
        
        if (record.getSketchSpecId() != null) {
            sql.VALUES("`sketch_spec_id`", "#{sketchSpecId,jdbcType=INTEGER}");
        }
        
        if (record.getDefaultSkuId() != null) {
            sql.VALUES("`default_sku_id`", "#{defaultSkuId,jdbcType=INTEGER}");
        }
        
        if (record.getImg() != null) {
            sql.VALUES("`img`", "#{img,jdbcType=VARCHAR}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.VALUES("`discount_price`", "#{discountPrice,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("`description`", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getTags() != null) {
            sql.VALUES("`tags`", "#{tags,jdbcType=VARCHAR}");
        }
        
        if (record.getIsTest() != null) {
            sql.VALUES("`is_test`", "#{isTest,jdbcType=TINYINT}");
        }
        
        if (record.getSpuThemeImg() != null) {
            sql.VALUES("`spu_theme_img`", "#{spuThemeImg,jdbcType=OTHER}");
        }
        
        if (record.getForThemeImg() != null) {
            sql.VALUES("`for_theme_img`", "#{forThemeImg,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String selectByExample(SpuExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`title`");
        sql.SELECT("`subtitle`");
        sql.SELECT("`category_id`");
        sql.SELECT("`root_category_id`");
        sql.SELECT("`online`");
        sql.SELECT("`create_time`");
        sql.SELECT("`update_time`");
        sql.SELECT("`delete_time`");
        sql.SELECT("`price`");
        sql.SELECT("`sketch_spec_id`");
        sql.SELECT("`default_sku_id`");
        sql.SELECT("`img`");
        sql.SELECT("`discount_price`");
        sql.SELECT("`description`");
        sql.SELECT("`tags`");
        sql.SELECT("`is_test`");
        sql.SELECT("`spu_theme_img`");
        sql.SELECT("`for_theme_img`");
        sql.FROM("spu");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Spu record = (Spu) parameter.get("record");
        SpuExample example = (SpuExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("spu");
        
        if (record.getId() != null) {
            sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getSubtitle() != null) {
            sql.SET("`subtitle` = #{record.subtitle,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryId() != null) {
            sql.SET("`category_id` = #{record.categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.SET("`root_category_id` = #{record.rootCategoryId,jdbcType=INTEGER}");
        }
        
        if (record.getOnline() != null) {
            sql.SET("`online` = #{record.online,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("`price` = #{record.price,jdbcType=VARCHAR}");
        }
        
        if (record.getSketchSpecId() != null) {
            sql.SET("`sketch_spec_id` = #{record.sketchSpecId,jdbcType=INTEGER}");
        }
        
        if (record.getDefaultSkuId() != null) {
            sql.SET("`default_sku_id` = #{record.defaultSkuId,jdbcType=INTEGER}");
        }
        
        if (record.getImg() != null) {
            sql.SET("`img` = #{record.img,jdbcType=VARCHAR}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{record.discountPrice,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("`description` = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getTags() != null) {
            sql.SET("`tags` = #{record.tags,jdbcType=VARCHAR}");
        }
        
        if (record.getIsTest() != null) {
            sql.SET("`is_test` = #{record.isTest,jdbcType=TINYINT}");
        }
        
        if (record.getSpuThemeImg() != null) {
            sql.SET("`spu_theme_img` = #{record.spuThemeImg,jdbcType=OTHER}");
        }
        
        if (record.getForThemeImg() != null) {
            sql.SET("`for_theme_img` = #{record.forThemeImg,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("spu");
        
        sql.SET("`id` = #{record.id,jdbcType=INTEGER}");
        sql.SET("`title` = #{record.title,jdbcType=VARCHAR}");
        sql.SET("`subtitle` = #{record.subtitle,jdbcType=VARCHAR}");
        sql.SET("`category_id` = #{record.categoryId,jdbcType=INTEGER}");
        sql.SET("`root_category_id` = #{record.rootCategoryId,jdbcType=INTEGER}");
        sql.SET("`online` = #{record.online,jdbcType=TINYINT}");
        sql.SET("`create_time` = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`update_time` = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("`delete_time` = #{record.deleteTime,jdbcType=TIMESTAMP}");
        sql.SET("`price` = #{record.price,jdbcType=VARCHAR}");
        sql.SET("`sketch_spec_id` = #{record.sketchSpecId,jdbcType=INTEGER}");
        sql.SET("`default_sku_id` = #{record.defaultSkuId,jdbcType=INTEGER}");
        sql.SET("`img` = #{record.img,jdbcType=VARCHAR}");
        sql.SET("`discount_price` = #{record.discountPrice,jdbcType=VARCHAR}");
        sql.SET("`description` = #{record.description,jdbcType=VARCHAR}");
        sql.SET("`tags` = #{record.tags,jdbcType=VARCHAR}");
        sql.SET("`is_test` = #{record.isTest,jdbcType=TINYINT}");
        sql.SET("`spu_theme_img` = #{record.spuThemeImg,jdbcType=OTHER}");
        sql.SET("`for_theme_img` = #{record.forThemeImg,jdbcType=VARCHAR}");
        
        SpuExample example = (SpuExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Spu record) {
        SQL sql = new SQL();
        sql.UPDATE("spu");
        
        if (record.getTitle() != null) {
            sql.SET("`title` = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getSubtitle() != null) {
            sql.SET("`subtitle` = #{subtitle,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryId() != null) {
            sql.SET("`category_id` = #{categoryId,jdbcType=INTEGER}");
        }
        
        if (record.getRootCategoryId() != null) {
            sql.SET("`root_category_id` = #{rootCategoryId,jdbcType=INTEGER}");
        }
        
        if (record.getOnline() != null) {
            sql.SET("`online` = #{online,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("`update_time` = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeleteTime() != null) {
            sql.SET("`delete_time` = #{deleteTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("`price` = #{price,jdbcType=VARCHAR}");
        }
        
        if (record.getSketchSpecId() != null) {
            sql.SET("`sketch_spec_id` = #{sketchSpecId,jdbcType=INTEGER}");
        }
        
        if (record.getDefaultSkuId() != null) {
            sql.SET("`default_sku_id` = #{defaultSkuId,jdbcType=INTEGER}");
        }
        
        if (record.getImg() != null) {
            sql.SET("`img` = #{img,jdbcType=VARCHAR}");
        }
        
        if (record.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{discountPrice,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("`description` = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getTags() != null) {
            sql.SET("`tags` = #{tags,jdbcType=VARCHAR}");
        }
        
        if (record.getIsTest() != null) {
            sql.SET("`is_test` = #{isTest,jdbcType=TINYINT}");
        }
        
        if (record.getSpuThemeImg() != null) {
            sql.SET("`spu_theme_img` = #{spuThemeImg,jdbcType=OTHER}");
        }
        
        if (record.getForThemeImg() != null) {
            sql.SET("`for_theme_img` = #{forThemeImg,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, SpuExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}