package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.SpuTag;
import com.guoyuhang.wx_cms.dao.model.SpuTagExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SpuTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuTagSqlProvider.class, method="countByExample")
    long countByExample(SpuTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SpuTagSqlProvider.class, method="deleteByExample")
    int deleteByExample(SpuTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_tag",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_tag (`spu_id`, `tag_id`)",
        "values (#{spuId,jdbcType=INTEGER}, #{tagId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SpuTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @InsertProvider(type=SpuTagSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(SpuTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @SelectProvider(type=SpuTagSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="tag_id", property="tagId", jdbcType=JdbcType.INTEGER)
    })
    List<SpuTag> selectByExample(SpuTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `spu_id`, `tag_id`",
        "from spu_tag",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="tag_id", property="tagId", jdbcType=JdbcType.INTEGER)
    })
    SpuTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuTagSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SpuTag record, @Param("example") SpuTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuTagSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SpuTag record, @Param("example") SpuTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SpuTagSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SpuTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_tag
     *
     * @mbg.generated
     */
    @Update({
        "update spu_tag",
        "set `spu_id` = #{spuId,jdbcType=INTEGER},",
          "`tag_id` = #{tagId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuTag record);
}