package com.guoyuhang.wx_cms.dao.mapper;

import com.guoyuhang.wx_cms.dao.model.ThemeSpu;
import com.guoyuhang.wx_cms.dao.model.ThemeSpuExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ThemeSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @SelectProvider(type=ThemeSpuSqlProvider.class, method="countByExample")
    long countByExample(ThemeSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ThemeSpuSqlProvider.class, method="deleteByExample")
    int deleteByExample(ThemeSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from theme_spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into theme_spu (`theme_id`, `spu_id`)",
        "values (#{themeId,jdbcType=INTEGER}, #{spuId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ThemeSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @InsertProvider(type=ThemeSpuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ThemeSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @SelectProvider(type=ThemeSpuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="theme_id", property="themeId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER)
    })
    List<ThemeSpu> selectByExample(ThemeSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `theme_id`, `spu_id`",
        "from theme_spu",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="theme_id", property="themeId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER)
    })
    ThemeSpu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ThemeSpuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ThemeSpu record, @Param("example") ThemeSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ThemeSpuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ThemeSpu record, @Param("example") ThemeSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ThemeSpuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ThemeSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_spu
     *
     * @mbg.generated
     */
    @Update({
        "update theme_spu",
        "set `theme_id` = #{themeId,jdbcType=INTEGER},",
          "`spu_id` = #{spuId,jdbcType=INTEGER}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ThemeSpu record);
}